---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "Jarom Bradshaw"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Introduction

<!-- highlight line 31 to the end and use ctrl + / (win) or command + / (mac) to uncomment out the code below, the same shortcut can be used to comment out code again. -->

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


### Elevator pitch

The most important thing learned in this project is learning how to incoporate github and other tools and libraries into our code. No matter where you code, you will be able to find so many valuable resources online, so researching them increases your ability to use them. The ability to research on my own allowed me to help complete this project and future projects as well; therefore, practicing research here and learning about all the resources available is valuable.

```{python}
#| label: project-data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```


### QUESTION|TASK 1

__Finish the Course Setup, and post any questions to getting your environment working smoothly in your course Slack channel__

I was able to finish the Course Setup, mostly on my own. I was unable to get the sql part to work. While everything is working now, I may need some further help. I plan to go to the DS lab to make sure I can redo this all on my new laptop which got here yesterday. 

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
# Include import statements here 
# Include reading data statements here

```

```{python}
#| label: Q1-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = px.scatter(df.head(200),
    x="name", 
    y="AK"
)
chart
```

I had to comment out the code I used as it was bugging.

```{python}
#| label: Q1-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here

# mydat = df.head(1000)\
#     .groupby('year')\
#     .sum()\
#     .reset_index()\
#     .tail(10)\
#     .filter(["year", "AK","AR"])

# display(mydat)

```



### QUESTION|TASK 2

__Recreate the example chart from PY4DS: CH2 Data Visualization of the textbook__



```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here

import pandas as pd
from palmerpenguins import load_penguins
from lets_plot import *

LetsPlot.setup_html()

(
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="island"))
)
```

```{python}
#| label: Q2-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = px.bar(df.head(200),
    x="name", 
    y="AK"
)
chart.show()
```



```{python}
#| label: Q2-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

```



### QUESTION|TASK 3

__Include the table created from PY4DS: CH2 Data Visualization used to create the above chart__

I had several bugs while doing this part of the project. I watched both of the videos you put in slack, read all of the readings and was unable to correctly put up any graph. I apologize.

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here


```

```{python}
#| label: Q3-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = px.bar(df.head(200),
    x="name", 
    y="AK"
)
chart.show()
```


```{python}
#| label: Q3-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

``` 
